FROM node:lts-alpine as build-stage

ARG VITE_URL_API
ENV VITE_URL_API ${VITE_URL_API}

WORKDIR /app
COPY src/vue-app/package*.json ./
RUN npm install

COPY src/vue-app/. .
RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]